---
.github/workflows/ci.yml:
  with:
    additional_packages: libaugeas-dev augeas-tools
    beaker_hypervisor: vagrant_libvirt
    acceptance_runs_on: macarne
    install_vagrant_dependencies: false
Gemfile:
  optional:
    ':test':
      - gem: ruby-augeas
spec/spec_helper.rb:
  spec_overrides:
    - "require 'augeas_spec'"
    - "# augeasproviders: setting $LOAD_PATH to work around broken type autoloading"
    - "$LOAD_PATH.unshift(File.join(__dir__, 'fixtures/modules/augeasproviders_core/lib'))"
