HOSTS:
  el7:
    roles:
      - default
      - grub2
    platform:   el-7-x86_64
    box:        generic/centos7
    hypervisor: vagrant

  el8:
    roles:
      - grub2
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: vagrant

# el6:
#   roles:
#     - grub
#   platform:   el-6-x86_64
#   box:        puppetlabs/centos-6.6-64-nocm
#   box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
#   hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  ## vb_gui: true
